# Generated by Django 4.2.3 on 2023-07-10 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('principle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_start_date', models.DateField()),
                ('number_of_payments', models.IntegerField()),
                ('periodicity', models.CharField(max_length=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.payment')),
            ],
        ),
    ]
