# Generated by Django 4.2.3 on 2023-07-10 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentschedule',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_schedule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='credit.paymentschedule'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
